#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'mysql'
cookbook 'nodejs', git: 'https://github.com/redguide/nodejs'
cookbook 'rbenv', git: 'https://github.com/fnichol/chef-rbenv'
cookbook 'runit'
cookbook 'ruby_build', git: 'https://github.com/fnichol/chef-ruby_build'
cookbook 'vim'
